[package]
name = "reducer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
log = "0.4.27"
env_logger = "0.10"
sqlparser = "0.56.0"
once_cell = "1.18"
anyhow = "1.0.98"
